name: CI
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Prepare Buildozer cache & bin dirs
        run: |
          mkdir -p .buildozer bin
          chmod -R 777 .buildozer bin

      - name: Get Date
        id: get-date
        run: echo "date=$(date -u +%Y%m%d)" >> $GITHUB_OUTPUT

      - name: Cache Buildozer global dir
        uses: actions/cache@v3
        with:
          path: .buildozer_global
          key: buildozer-global-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}
          restore-keys: buildozer-global-

      - name: Cache Buildozer workdir
        uses: actions/cache@v3
        with:
          path: .buildozer
          key: buildozer-${{ runner.os }}-${{ steps.get-date.outputs.date }}-${{ hashFiles('buildozer.spec') }}
          restore-keys: buildozer-${{ runner.os }}-${{ steps.get-date.outputs.date }}-

      - name: Build APK with Docker Buildozer
        run: |
          docker pull ghcr.io/kivy/buildozer:latest

          docker run --rm \
            --entrypoint bash \
            -v "${{ github.workspace }}":/home/user/hostcwd \
            -w /home/user/hostcwd \
            ghcr.io/kivy/buildozer:latest \
            -c " \
              export ANDROID_SDK_ROOT=/home/user/.buildozer/android/platform/android-sdk && \
              mkdir -p \$ANDROID_SDK_ROOT/cmdline-tools && \
              cd \$ANDROID_SDK_ROOT/cmdline-tools && \
              wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip && \
              unzip -q cmdline-tools.zip && \
              mv cmdline-tools latest && \
              export PATH=\$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:\$PATH && \
              yes | sdkmanager --sdk_root=\$ANDROID_SDK_ROOT 'platform-tools' 'build-tools;36.0.0' 'platforms;android-30' && \
              yes | sdkmanager --sdk_root=\$ANDROID_SDK_ROOT --licenses && \
              buildozer android debug \
            "

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package
          path: bin/*.apk
